### ISSUE TITLE
Issue1

### ISSUE THREAD

**Issue by enricoperissinotto1** [mandeep/Job-Automate#3]
jobautomate --key 9126875254295199 "Bender" "Rodriguez" "bender@ilovebender.com" "Metalworking" "1.pdf" "Miami"
Traceback (most recent call last):
  File "/usr/local/bin/jobautomate", line 9, in <module>
    load_entry_point('jobautomate==0.18.10', 'console_scripts', 'jobautomate')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.macosx-10.13-intel/egg/jobautomate/commandline.py", line 192, in cli
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/lk/wyy4dwl154qdvxq96hgb56f00000gn/T/tmpiwB61I If you specified a log_file in the FirefoxBinary constructor, check it for details.

any ideas would be appreciated

**Comment by mandeep** [comment]
Seems to be a problem with your Firefox install. Which Firefox version are you using?
